package com.orderflow.orderservice.api;
import com.orderflow.contracts.*; import com.orderflow.orderservice.domain.*; import org.springframework.http.*; import org.springframework.kafka.core.KafkaTemplate; import org.springframework.web.bind.annotation.*; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api/orders") public class OrderController {
 private final OrderRepository orders; private final SagaHistoryRepository history; private final KafkaTemplate<String,Object> kafka;
 public OrderController(OrderRepository o,SagaHistoryRepository h,KafkaTemplate<String,Object> k){orders=o;history=h;kafka=k;}
 @PostMapping public ResponseEntity<OrderDocument> create(@RequestBody CreateOrderRequest req){ if(req.products()==null||req.products().isEmpty()) return ResponseEntity.badRequest().build(); OrderDocument o=new OrderDocument(); o.transactionId=UUID.randomUUID().toString(); o.products=req.products(); o.status="PENDING"; o.createdAt=Instant.now(); o=orders.save(o); BigDecimal total=o.products.stream().map(p->p.unitValue().multiply(BigDecimal.valueOf(p.quantity()))).reduce(BigDecimal.ZERO,BigDecimal::add); int items=o.products.stream().mapToInt(ProductItem::quantity).sum(); OrderPayload payload=new OrderPayload(o.id,o.products,total,items); SagaEvent e=new SagaEvent(UUID.randomUUID().toString(),o.transactionId,o.id,SagaStep.ORDER,SagaStatus.STARTED,"Saga started",payload,Instant.now()); kafka.send(Topics.START,o.id,e); return ResponseEntity.status(HttpStatus.ACCEPTED).body(o); }
 @GetMapping("/{id}") public ResponseEntity<OrderDocument> get(@PathVariable String id){return ResponseEntity.of(orders.findById(id));}
 @GetMapping("/sagas") public ResponseEntity<SagaHistory> saga(@RequestParam(required=false) String orderId,@RequestParam(required=false) String transactionId){ Optional<SagaHistory> r=orderId!=null?history.findByOrderId(orderId):transactionId!=null?history.findByTransactionId(transactionId):Optional.empty(); return ResponseEntity.of(r); }
}
